### ISSUE TITLE
Amazon Sync Error

### ISSUE THREAD

**Issue by Reedyuk** [bitrise-io/steps-amazon-s3-upload#10]
Hi,
I am running the S3 Sync step, but I'm getting an error but i can't actually see the error, see the log below:

+------------------------------------------------------------------------------+
| (2) amazon-s3-upload@3.1.2                                                   |
+------------------------------------------------------------------------------+
| id: amazon-s3-upload                                                         |
| version: 3.1.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-06-23T07:45:58-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[07:46:01] (awscli) isn't installed, installing...      
INFO[07:46:11]  * [OK] awscli installed          
INFO[07:46:11]  * [OK] Step dependency (awscli) installed, available. 

Configs:
  * access_key_id: ***
  * secret_access_key: ***
  * upload_bucket: nm-mobile-resources
  * upload_local_path: IPA/
  * acl_control: private
  * set_acl_only_on_changed_objets: true
  * aws_region: 

/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise419836257/step_src/step.sh: line 123: print_failed_message: command not found
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | amazon-s3-upload@3.1.2 (exit code: 127)                      | 15 sec   |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-amazon-s3-upload/issues   |
| Source: https://github.com/bitrise-io/steps-amazon-s3-upload                 |
+----+--------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment]
Thanks for reporting! We'll look into it ASAP!

**Comment by godrei** [comment]
Hi @Reedyuk ,
we fixed the issue, [new release](https://github.com/bitrise-io/steps-amazon-s3-upload/releases/tag/3.1.3) will be available in steplib soon.

Thanks for reporting!
